[env:uno]
platform  = atmelavr
board     = uno
framework = arduino

; Point PlatformIO at our own src/inc folders
build_src_dir = firmware/src
build_flags   =
    -I firmware/inc
    -I firmware/config
    -std=gnu99

; No Arduino libs — we use bare AVR
build_unflags = -DARDUINO